### ISSUE TITLE
Partial render consul KV

### ISSUE THREAD

**Issue by misbahulard** [heronimus/ct-plugin-string2files#4]
Glad to see that you just release `0.1.1` version that support musl for Alpine linux, but we got a new problem.

The problem is when you try to render nested KV, it doesn't render all KV and you need to run and run again until all KV rendered.

our kv structure is
```
nginx-conf/
├── domain-conf
│   ├── api-docs.conf
│   ├── api-sandbox.conf
│   ├── app-mobile.conf
│   ├── app.conf
│   ├── cms.conf
│   └── binding.conf
├── gzip-comp.conf
└── nginx.conf
```

and if we try to render using this plugin sometime is just render `nginx.conf` or some file, but we don't get any problem in previous `0.1.0` version. 

Thanks for work @heronimus 👍

**Comment by heronimus** [comment]
Hi @misbahulard, thanks for the report. I can confirm this behaviour is reproducable using v0.1.1 musl release on Alpine environment.

While using standard/glibc version is okay, I believe it's related with V compiler config with musl, for now please use the [musl-debug](https://github.com/heronimus/ct-plugin-string2files/releases/download/v0.1.1/string2files-v0.1.1-linux-amd64-musl-debug) release file, as I tested, it's work fine. Or if you want to build the binary by yourself, please add `-g` to the compiler flags which will generate debugging symbols in your executable. 

I'll try to investigate and report this behavior as V issue, I'll let you know for update.

**Comment by Eslamanwar** [comment]
Any update on this bug , Thank you for your great work

**Comment by heronimus** [comment]
Hi @Eslamanwar, apparently this bug comes from _V_ compiler for _musl_ environment. I haven't check this again, but for now, there's 2 option you can try:

1. Use debug compiled release for musl [[this]](https://github.com/heronimus/ct-plugin-string2files/releases/download/v0.1.1/string2files-v0.1.1-linux-amd64-musl-debug) (last time I try, I haven't found any problem).
or
2. Install gcc to your alpine container (https://wiki.alpinelinux.org/wiki/GCC), and use default binary release.

I'll check this issue again later after update my V compiler, thanks!

**Comment by heronimus** [comment]
Fixed in PR https://github.com/heronimus/ct-plugin-string2files/pull/5
